// components/NewOptionsList.tsx
import { useMemo } from "react";

export const NEW_OPTION_IDS = [
        // 0.36.0
        "bomb-collars",
        "bondage-permanency",
        "bone-breaking",
        "cast-bondage",
        "clitboxes",
        "consensual-possession",
        "cum-assimilation",
        "cum-play",
        "dickboxes",
        "dilf-tf",
        "dove-fucking",
        "featurelessness",
        "female-fleshpits",
        "forced-futanarization",
        "full-body-casts",
        "full-body-stimulation",,
        "futanarization",
        "general-detachment",
        "head-detachment",
        "inflatable-toys",
        "male-cuntboy-tf",
        "male-fleshpits",
        "maternity-panties",
        "milf-tf",
        "navel-fucking",
        "nursing-bras",
        "overheard-sex",
        "pec-to-tit-docking",
        "protective-suits",
        "pussy-tongues",
        "auto-dove-fucking",
        "sensitivity-development",
        "shedding",
        "sleepsacks",
        "tortured-boys",
        "tortured-girls",
        "wall-of-dicks",
        "web-cocoons",
        // 0.35.0
        "addiction",
        "animal-hypnosis",
        "aware-hypnosis",
        "blank-eyes",
        "body-controllers",
        "chloroform",
        "chocolate",
        "constriction",
        "decapitation",
        "demons",
        "double-vision",
        "drugged-peril",
        "false-hypnosis",
        "finger-snapping",
        "full-blank-hypnosis",
        "futa-fluffing",
        "head-inflation",
        "headless-female",
        "headless-male",
        "hiccuping",
        "hypnotic-dancing",
        "knocked-silly",
        "masochism-from-evil",
        "masochism-from-good",
        "masochism-porn",
        "monkey-paw-wishes",
        "mutual-docking",
        "mutual-gaining-observer",
        "mutual-gaining-participant",
        "non-sexual-masochism",
        "non-sexual-sadism",
        "nonhuman-domination",
        "perilous-hypnosis",
        "personality-overwriting",
        "porn-addiction",
        "practical-hypnosis",
        "reality-warping",
        "reprogramming",
        "ring-eyes",
        "sadism-on-evil",
        "sadism-on-good",
        "sadism-on-masochist",
        "sadism-on-sadist",
        "sadism-porn",
        "scat-torture",
        "sleepwalking",
        "snoring",
        "spirals",
        "subliminals",
        "tranquilizer-darts",
        "trigger-phrases",
        "unaware-hypnosis",
        "vore-observer",
        "white-eyes",
        "zombiewalking",
        
];

export function useNewOptions() {
  return useMemo(() => NEW_OPTION_IDS, []);
}