// components/NewOptionsList.tsx
import { useMemo } from "react";

export const NEW_OPTION_IDS = [
        // 0.35.0
        "addiction",
        "animal-hypnosis",
        "aware-hypnosis",
        "blank-eyes",
        "body-controllers",
        "chloroform",
        "chocolate",
        "constriction",
        "decapitation",
        "demons",
        "double-vision",
        "drugged-peril",
        "false-hypnosis",
        "finger-snapping",
        "full-blank-hypnosis",
        "futa-fluffing",
        "head-inflation",
        "headless-female",
        "headless-male",
        "hiccuping",
        "hypnotic-dancing",
        "knocked-silly",
        "masochism-from-evil",
        "masochism-from-good",
        "masochism-porn",
        "monkey-paw-wishes",
        "mutual-docking",
        "mutual-gaining-observer",
        "mutual-gaining-participant",
        "non-sexual-masochism",
        "non-sexual-sadism",
        "nonhuman-domination",
        "perilous-hypnosis",
        "personality-overwriting",
        "porn-addiction",
        "practical-hypnosis",
        "reality-warping",
        "reprogramming",
        "ring-eyes",
        "sadism-on-evil",
        "sadism-on-good",
        "sadism-on-masochist",
        "sadism-on-sadist",
        "sadism-porn",
        "scat-torture",
        "sleepwalking",
        "snoring",
        "spirals",
        "subliminals",
        "tranquilizer-darts",
        "trigger-phrases",
        "unaware-hypnosis",
        "vore-observer",
        "white-eyes",
        "zombiewalking",


        // 0.34.1
        "cock-milking-milked-r",
        "cock-milking-milker",
        "fat-pokemon",
        "feederism-stuffing-r",
        "feederism-stuffing",
        "gagging-r",

        // 0.34.0
        "alpha-couple-dynamic",
        "auto-thighjobs",
        "bar-theme",
        "barbed-cocks",
        "buried-genitals",
        "beta-humiliation",
        "breast-growth-hormones",
        "body-exploration",
        "bra-sniffing",
        "brutal-raceplay",
        "bwcs",
        "clicker-training",
        "crate-training",
        "death-feederism-r",
        "death-feederism",
        "discipline",
        "dommebreaking",
        "ephebophilia",
        "extreme-musk",
        "extreme-pregnancies",
        "flaccid-play",
        "food-tasks",
        "foreskin-worship",
        "fupas",
        "hands-free-orgasms",
        "touch-free-orgasms",
        "hebephilia",
        "height-humiliation",
        "husband-humiliation",
        "high-protocol",
        "instant-hookups",
        "immobilization-weight",
        "lewd-asmr",
        "laboratory-theme",
        "locker-room-theme",
        "long-fingernails",
        "long-toenails",
        "looning-b2p",
        "looning-np",
        "mating-press",
        "mursuits",
        "nightclub-theme",
        "oiled-asses",
        "oiled-chests",
        "oiled-feet",
        "oiled-tits",
        "onomatopoeia",
        "ouji",
        "pedophilia",
        "pregnancy-risk",
        "pregnant-bellies",
        "prehensile-cocks",
        "premature-humiliation",
        "queefing",
        "sexual-exhaustion",
        "sharp-teeth",
        "sneaky-sex",
        "soft-raceplay",
        "submissive-tasks",
        "tantric-sex",
        "weight-humiliation",
        "wife-humiliation",
        
];

export function useNewOptions() {
  return useMemo(() => NEW_OPTION_IDS, []);
}